import { NAV_TYPES } from "../store/slices/layoutSlice";

export const navigation = {
  type: NAV_TYPES.SIDE,
  items: [
    {
      id: "dashboard",
      label: "Dashboard",
      icon: "HomeIcon",
      path: "/dashboard",
      badge: null,
      type: "item",
    },
    {
      id: "management",
      label: "Management",
      icon: "BuildingOfficeIcon",
      type: "menu",
      isOpen: false,
      items: [
        {
          id: "company",
          label: "Company",
          icon: "BuildingOfficeIcon",
          path: "/company",
          badge: null,
          type: "item",
        },
        {
          id: "users",
          label: "Users",
          icon: "UsersIcon",
          path: "/users",
          badge: null,
          type: "item",
        },
        {
          id: "branches",
          label: "Branches",
          icon: "BuildingStorefrontIcon",
          path: "/branches",
          badge: null,
          type: "item",
        },
        {
          id: "roles",
          label: "Roles",
          icon: "ShieldCheckIcon",
          path: "/roles",
          badge: null,
          type: "item",
        },
      ],
    },
    {
      id: "lease",
      label: "Lease",
      icon: "BuildingOfficeIcon",
      type: "menu",
      isOpen: false,
      items: [
        {
          id: "lease-accounts",
          label: "Accounts",
          icon: "BuildingOfficeIcon",
          path: "/lease/accounts",
          badge: null,
          type: "item",
        },
        {
          id: "lease-installments",
          label: "Installments",
          icon: "ChartBarIcon",
          path: "/lease/installments",
          badge: null,
          type: "item",
        },
        {
          id: "lease-outstand",
          label: "Outstand",
          icon: "ExclamationTriangleIcon",
          path: "/lease/outstand",
          badge: null,
          type: "item",
        },
      ],
    },
    {
      id: "catalog",
      label: "Catalog",
      icon: "CubeIcon",
      type: "menu",
      isOpen: false,
      items: [
        {
          id: "brands",
          label: "Brands",
          icon: "TagIcon",
          path: "/brands",
          badge: null,
          type: "item",
        },
        {
          id: "categories",
          label: "Categories",
          icon: "Squares2X2Icon",
          path: "/categories",
          badge: null,
          type: "item",
        },
        {
          id: "products",
          label: "Products",
          icon: "CubeIcon",
          path: "/products",
          badge: null,
          type: "item",
        },
        {
          id: "accounts",
          label: "Accounts",
          icon: "Squares2X2Icon",
          path: "/accounts",
          badge: null,
          type: "item",
        },
      ],
    },
    // {
    //   id: "analytics",
    //   label: "Analytics",
    //   icon: "ChartBarIcon",
    //   path: "/analytics",
    //   badge: null,
    //   type: "item",
    // },
    // {
    //   id: "sidebar-colors",
    //   label: "Sidebar Colors",
    //   icon: "CogIcon",
    //   path: "/sidebar-colors",
    //   badge: null,
    //   type: "item",
    // },
    // {
    //   id: "spinner-showcase",
    //   label: "Spinner Showcase",
    //   icon: "ArrowPathIcon",
    //   path: "/spinner-showcase",
    //   badge: null,
    //   type: "item",
    // },
    {
      id: "settings",
      label: "Settings",
      icon: "CogIcon",
      path: "/settings",
      badge: null,
      type: "item",
    },
    // {
    //   id: "pos",
    //   label: "POS System",
    //   icon: "BuildingStorefrontIcon",
    //   type: "menu",
    //   isOpen: false,
    //   items: [
    //     {
    //       id: "pos-sales",
    //       label: "Sales",
    //       icon: "CubeIcon",
    //       path: "/pos/sales",
    //       badge: null,
    //       type: "item",
    //     },
    //     {
    //       id: "pos-inventory",
    //       label: "Inventory",
    //       icon: "CubeIcon",
    //       path: "/pos/inventory",
    //       badge: null,
    //       type: "item",
    //     },
    //     {
    //       id: "pos-transactions",
    //       label: "Transactions",
    //       icon: "CubeIcon",
    //       path: "/pos/transactions",
    //       badge: null,
    //       type: "item",
    //     },
    //   ],
    // },
    // {
    //   id: "tailor",
    //   label: "Tailor Management",
    //   icon: "UserCircleIcon",
    //   type: "menu",
    //   isOpen: false,
    //   items: [
    //     {
    //       id: "tailor-orders",
    //       label: "Orders",
    //       icon: "CubeIcon",
    //       path: "/tailor/orders",
    //       badge: null,
    //       type: "item",
    //     },
    //     {
    //       id: "tailor-measurements",
    //       label: "Measurements",
    //       icon: "CubeIcon",
    //       path: "/tailor/measurements",
    //       badge: null,
    //       type: "item",
    //     },
    //     {
    //       id: "tailor-fabric",
    //       label: "Fabric Inventory",
    //       icon: "CubeIcon",
    //       path: "/tailor/fabric-inventory",
    //       badge: null,
    //       type: "item",
    //     },
    //   ],
    // },
    // {
    //   id: "appointments",
    //   label: "Appointments",
    //   icon: "CalendarIcon",
    //   type: "menu",
    //   isOpen: false,
    //   items: [
    //     {
    //       id: "appointments-calendar",
    //       label: "Calendar",
    //       icon: "CubeIcon",
    //       path: "/appointments/calendar",
    //       badge: null,
    //       type: "item",
    //     },
    //     {
    //       id: "appointments-bookings",
    //       label: "Bookings",
    //       icon: "CubeIcon",
    //       path: "/appointments/bookings",
    //       badge: null,
    //       type: "item",
    //     },
    //     {
    //       id: "appointments-customers",
    //       label: "Customers",
    //       icon: "CubeIcon",
    //       path: "/appointments/customers",
    //       badge: null,
    //       type: "item",
    //     },
    //   ],
    // },
  ],
};
